### PR TITLE
Organizando acentos e pontuação

### PR DESCRIPTION
**Pull request by deboraazevedo**
organizando acentos e pontuação em let-the-games-begin.md e primeiro-passo.md  #6

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:
- Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)
- Pull request title must start with uppercase [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/I-am-Gabi/minicurso-intro-python/5/8219a6c2-d5b8-4016-827d-cdfa17622bc5/5a0ad952-8c65-4df5-89b7-cff88cfb3105) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by deboraazevedo** [comment]
Organizando acentos gráficos e pontuação dos arquivos primeiro-passo.md e let-the-games-begin.md

**Comment by ghost** [comment]
This pull request still violates some of our guidelines:
- Pull request title must start with uppercase [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/I-am-Gabi/minicurso-intro-python/5/8219a6c2-d5b8-4016-827d-cdfa17622bc5/5a0ad952-8c65-4df5-89b7-cff88cfb3105) for details.

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Pull request merged**
